import type { OutdatedSeverity } from "./compute-outdated";

export type OutdatedDepRow = {
  manifestPath: string;
  packageName: string;
  current: string;
  latest: string;
  severity: OutdatedSeverity;
  ecosystem: string;
};

const SEVERITY_ICON: Record<OutdatedSeverity, string> = {
  major: "🔴",
  minor: "🟠",
  patch: "🟡",
  prerelease: "🔵",
};

const MAX_ROWS = 100;

/**
 * Builds a markdown body listing outdated dependencies grouped by
 * manifest. Caps at MAX_ROWS to stay under GitHub's 65k issue body
 * limit; truncated lists get a "+N more" footer line.
 */
export function buildIssueBody(rows: OutdatedDepRow[]): string {
  if (rows.length === 0) return "All dependencies are up to date. 🎉";

  const trimmed = rows.slice(0, MAX_ROWS);
  const overflow = rows.length - trimmed.length;

  const byManifest = new Map<string, OutdatedDepRow[]>();
  for (const row of trimmed) {
    const list = byManifest.get(row.manifestPath) ?? [];
    list.push(row);
    byManifest.set(row.manifestPath, list);
  }

  const lines: string[] = [];
  lines.push("## Outdated dependencies");
  lines.push("");
  lines.push(
    "Generated by maureldev. Each row links current vs latest version reported by the upstream registry.",
  );
  lines.push("");

  for (const [manifest, list] of byManifest) {
    lines.push(`### \`${manifest}\``);
    lines.push("");
    lines.push("| | Package | Current | Latest | Severity |");
    lines.push("| - | --- | --- | --- | --- |");
    for (const row of list) {
      lines.push(
        `| ${SEVERITY_ICON[row.severity]} | \`${row.packageName}\` | \`${row.current}\` | \`${row.latest}\` | ${row.severity} |`,
      );
    }
    lines.push("");
  }

  if (overflow > 0) {
    lines.push(`_+${overflow} more outdated dependencies not shown._`);
  }

  return lines.join("\n");
}
